# Site
repository: sihyeonleee/sihyeonleee.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이시현 - si hyeon Lee
title: 1993. 05. 08 Developer
email: dltlgus313@naver.com
# email_title: Email (Email title override)
phone: 010-2381-4118
# phone_title: Phone (Phone title override)
website: https://sihyeonleee.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: sihyeonleee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: https://www.facebook.com/profile.php?id=100004964325600
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/jobs.JPG
about_content: | # this will include new lines to allow paragraphs
  <div style="font-size: 1.6rem; text-align: justify; margin-top: 30px;">
    책임감과 효율성을 중시하고 일상에서도 이를 실천하려고 노력합니다. 사적인 
    모임에서 사람들과 어울리는 것을 좋아하지만, 동시에 혼자만의 시간도 소중히 
    여깁니다. 다양한 사람들과의 교류를 통해 얻는 에너지와 혼자 있는 시간 동안의 
    깊은 사고가 제 삶을 균형 있게 만들어줍니다. 이러한 성향은 제 업무와 개인
    생활 모두에 긍정적인 영향을 미칩니다.
  </div>
  <div style="font-size: 200%; margin-top:35px;">
    <mark style="margin-left:3px;">JAVA</mark>
    <mark style="margin-left:3px;">Spring</mark>
    <mark style="margin-left:3px;">JSP</mark>
    <mark style="margin-left:3px;">Node.js</mark>
    <mark style="margin-left:3px;">Express</mark>
    <mark style="margin-left:3px;">React</mark>
    <mark style="margin-left:3px;">Javascript</mark>
    <mark style="margin-left:3px;">RDBMS</mark>
    <mark style="margin-left:3px;">Nifi</mark>
    <mark style="margin-left:3px;">Elasticsearch</mark>
    <mark style="margin-left:3px;">Git</mark>
    <mark style="margin-left:3px;">SVN</mark>
  </div>


  <div style="margin-top: 120px; margin-bottom: 30px; font-size: 1.5em; font-weight: 900; text-align: right;">
    <a href="https://sihyeonleee.github.io">원본 (git)</a>
    <span style="margin-left: 10px;margin-right: 10px;"> | </span>
    <a href="images/sihyeonleee.pdf" download="sihyeonlee">PDF 다운로드</a>
    <span style="margin-left: 10px;margin-right: 10px;"> | </span>
    <a href="images/sihyeonleee.docx" download="sihyeonlee">WORD 다운로드</a>
    <span style="margin-left: 10px;margin-right: 10px;"> | </span>
    <a href="images/sihyeonleee.pptx" download="sihyeonlee">PPT 다운로드</a>
  </div>

content:
  - title: Career
    layout: list
    content:
      - layout: left
        border: weak
        title: 가을엔터테인먼트
        sub_title: 웹개발팀 대리
        caption: 2024. 10 ~ <mark>재직중</mark>
        quote: >
          Java Spring Boot 웹개발
        description: |
          **1. 조이팬 - 팬과 크리에이터가 하나가 되는 공간**
          ---
          - **주요 업무:** 
          분석 및 db 설계를 포함한 웹개발 전체

          - **서버 구성:** 
          docker v27.3, apache v2.4, tomcat v11, spring boot v3.3, next.js v14.2, mysql v10.3, redis v7.4

          - **참여 내용:**
            1. 요구사항 분석 및 db 설계, 개발, 인프라 구성 및 구축 등
            2. SNS, JWT, nicepay 결제, 실시간 채팅, postfix, 도메인관리등 웹개발 전체

          - **`기여`:**

            미디어 컨텐츠를 보는 사이트 특성으로 큰 용량의 동영상파일을 업로드 하기 위한 과정
            - 전략 : Next 의 SPA 특성과, chunk 단위 업로드 후 최종 merge 하는 비동기 업로드 구현
            - **결과 : 파일 업로드 중 SPA 의 특성으로 페이지 전체 로딩이 되지않아 자유로운 활동이 가능**

      - layout: left
        border: weak
        title: I-Bricks
        sub_title: 지능정보개발본부 대리
        caption: 2023. 06 ~ 2024. 09 (1년 5개월)
        quote: >
          Elasticsearch 검색 개발
        description: |
          **1. LG임원인사 검색 시스템**
          ---
          - **주요 업무:** 
          빅데이터 색인 검색

          - **서버 구성:** 
          nodejs, elasticsearch, kibana, mssql

          - **참여 내용:**
            1. MSSQL 데이터 색인 수집기 개발 및 쿼리 작성
            2. 검색 필터 및 명령형 검색 NodeJS API 개발

          - **`기여`:**

            사내 권장 프로그램인 NiFi를 운영 서버 자원의 한계로 대처방안 개발 과정
            - 전략 : NodeJS 수집기 이용 Chunk 별 Bulk size 조절 및 데이터 백업
            - **결과 : 확보된 리소스만큼 메모리 증가와 데이터 백업에 여유분을 둘 수 있게 되었으며 고객만족 향상**

          **2. 이용장벽없는 스마트전시관 챗봇 응답 시스템**
          ---
          - **주요 업무:** 
          빅데이터 색인 검색

          - **서버 구성:** 
          nodejs, ejs, react, typescript, nifi, elasticsearch, kibana, nginx

          - **참여 내용:**
            1. React, TypeScript 챗봇 화면 개발
            2. Apache NiFi 데이터 색인 자동화
            3. 스테이지, 운영 서버간의 데이터 싱크를 위한 migration 프로그램 개발

          - **`기여`:**

            내부 서버와 고객사의 운영 서버간 데이터 싱크를 맞추기 위한 과정
            - 전략 : NodeJS, 쉘 스크립트를 이용한 마이그레이션
            - **결과 : 복잡한 인프라 구성에 따른 데이터 동기화 요청에 빠른 대응**

      - layout: left
        border: weak
        title: PCN
        sub_title: dv실 대리
        caption: 2022. 10 ~ 2023. 05 (7개월)
        quote: >
          Java Spring 웹개발
        description: |
          **1. 인사혁신처 발주 인재개발 플랫폼 3단계 구축**
          ---
          - **주요 업무:** 
          웹개발

          - **서버 구성:** 
          java, jsp, cubrid, git, jenkins, jboss

          - **참여 내용:**
            1. BIX5 대시보드 솔루션 활용 대시보드 개발
            2. kginicis 모듈 결제 및 취소, 환불 규정 적용
            3. 그외 POI 등 API 개발 참여

          - **`기여`:**

            배포 시 프로젝트 빌드후 배포하여 긴급 수정시 반영 속도를 개선하는 과정
            - 전략 : 수정 혹은 추가된 파일 대상으로 구조에 맞게 경로복사하여 덮어쓰기
            - **결과 : 수정된 파일대상으로 target 복사하여 배포 시간이 단축 및 실수 줄임**

          **2. 3D 상상포털 사이트내 공통게시판 구축**
          ---
          - **주요 업무:** 
          웹개발자

          - **서버 구성:** 
          java, jsp, mariadb, svn, tomcat

          - **참여 내용:**
            1. 공통게시판 구축
            2. 전역 레이아웃 구성
            3. 전역 페이지네이션 구성

      - layout: left
        title: UBION
        sub_title: 플랫폼개발2팀 대리
        caption: 2019. 01 ~ 2022. 04 (3년 3개월)
        quote: >
          Java Spring, NodeJs 웹개발
        description: |
          **1. EBS SW온라인 교육 플랫폼**
          ---
          - **주요 업무:** 
          웹개발

          - **서버 구성:** 
          java, jsp, nodeJs, ejs, redis, mysql, svn, docker, jboss

          - **참여 내용:**
            1. WebRTC 화상 강의 개발
            2. Aceditor 온라인 코딩 개발
            3. Socket 실시간 채팅 개발

          - **`기여`:**

            WebRTC 통신을 위해 사설네트워크(VPN), 방화벽이 구성된 환경에 대한 대응
            - 전략 : STUN/TURN 서버 구성 및 시그널 서버 구축
            - **결과 : 보안에 예민한 학교 및 기관에서도 화상강의를 진행 가능**

          **2. EBS SW온라인 클래스 - COVID19 대응 TF**
          ---
          - **주요 업무:** 
          웹개발

          - **서버 구성:** 
          java, jsp, mysql, git, docker, jboss

          - **참여 내용:**
            1. 통계 집계 Java App 개발 (로그 데이터 분석)
            2. Long Time Query 튜닝
            3. 그외 사이트 개발 및 유지보수

          - **`기여`:**

            고객 요청으로 수억건에 해당하는 로그 집계를 도와주는 자동화 프로그램 개발
            - 전략 : 버튼형식으로 누구든 통계를 뽑을수 있는 프로그램 개발
            - **결과 : 통계 업무처리가 개발자의 영역을 벗어나게 되어 업무 집중 향상**

          **3. 거점국립대학 학점 교류 시스템(KERIS)**
          ---
          - **주요 업무:** 
          웹개발

          - **서버 구성:** 
          java, jsp, svn, tomcat, mysql

          - **참여 내용:**
            1. jsp 화면 및 백엔드 개발
            2. 사이트 리뉴얼 디자인 적용

          **4. LMS 교육 플랫폼 Hydee**
          ---
          - **주요 업무:** 
          웹개발

          - **서버 구성:** 
          nodeJs, redis, mysql, git, jenkins, kubernetes, msa, multitenant

          - **참여 내용:**
            1. JWT 로그인 및 세션 체크 미들웨어 개발
            2. SocketIO, Redis 활용 실시간 퀴즈풀이 개발
            3. 온라인 교육 수업에 대한 설계, 예약, 뷰어 개발

          - **`기여`:**

            multitenant 도입으로 효율적인 커넥션 관리를 위한 과정
            - 전략 : knex, cls, cache 를 이용하여 커넥션 타임을 설정하여 캐싱 관리.
            - **결과 : kubernetes 의 수평적 확장성에 따른 리소스 절약 가능**
  - title: Portfolio
    layout: list
    content:
      - layout: left
        title: 대화형 모델
        caption: sLLM(llama)
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          wsl, llama-cpp, python

          **주요 기능 :**
          sLLM(llama) 모델을 이용한 대화형 모델 구현

          **상세 설명 :**
          Window11 의 가상화 wsl 환경에서 llama + 언어모델을 이용한 대화형 모델 구현.
          속도 개선을 위해 GPU 사용 하였으며 가벼운 테스트를 위해 mistral.gguf 모델 사용.


          **Link :**
          <a href="https://canyon-nickel-820.notion.site/sLLM-llama-cpp-1c0db14395b780e28d2ffdb0e02fd3a7?pvs=74">[notion] sLLM(llama)</a>

      - layout: left
        title: 이미지 유사검색
        caption: CLIP + FAISS
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          Python, Pytorch, Huggingface, Faiss

          **주요 기능 :**
          CLIP 모델을 이용한 이미지 벡터화 및 Faiss 를 이용한 유사도 검색

          **상세 설명 :**
          CLIP은 이미지와 텍스트를 같은 벡터 공간에 임베딩하여 유사도를 계산할 수 있게 해줍니다.
          FAISS는 Facebook AI Research에서 개발한 라이브러리로, 대규모 벡터 데이터셋에서 빠른 유사도 검색을 수행할 수 있습니다.
          CLIP으로 생성된 벡터들을 FAISS 인덱스에 저장하고 검색하는 방식으로 활용됩니다.

          **Link :**
          <a href="https://canyon-nickel-820.notion.site/CLIP-FAISS-1bcdb14395b7802780ead79214068fbf?pvs=73">[notion] CLIP + FAISS 유사검색(한글지원)</a>

      - layout: left
        title: 화상회의 프로그램
        caption: WebRTC
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          JavaScript, Node.js, Express, Socket.io, RTCMultiConnection

          **주요 기능 :**
          p2p 실시간 통신, 영상 및 음성, 화면공유 스트리밍, 채팅 기능, 파일 공유 기능

          **상세 설명 :**
          WebRTC, coturn 활용하여 실시간 화상회의 프로그램 개발
          브라우저 간 P2P연결(연결불가시 coturn:TURN 서버 우회)을 통한 영상 및 음성 데이터 실시간 전송
          그밖의 텍스트 전송을 이용해 canvas의 그리기 공유도 가능

          **Link :**
          <a href="https://canyon-nickel-820.notion.site/webRTC-coturn-4a89d7b420634d6aa46ea4d96160fc9f?pvs=74">[notion] webrtc</a>

      - layout: left
        title: 단어예측(유사검색) 프로그램
        caption: Word2Vec(Skip-gram, CBOW)
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          Node.js, JavaScript, Express

          **주요 기능 :**
          대규모 텍스트 데이터 전처리 및 Skip-gram 및 CBOW 알고리즘 구현, 
          입력된 단어 및 문장에 대한 유사한 단어를 예측

          **상세 설명 :**
          자연어 처리(NLP) 작업의 일환으로, Word2Vec 모델을 사용하여 단어 임베딩을 생성, Skip-gram과 
          CBOW(Continuous Bag of Words) 알고리즘을 구현하여 대규모 텍스트 데이터로부터 단어 벡터를 학습하고
          사용자 입력에 대한 데이터와 유사한 데이터를 코사인유사도를 통해 확인 가능.

          **Link :**
          - <a href="https://canyon-nickel-820.notion.site/javascript-word2vector-skip-gram-701bd2dcaa2443f094da59d598b321e1?pvs=74">[notion] skip-gram</a>
          - <a href="https://canyon-nickel-820.notion.site/javascript-word2vector-CBOW-9a038ab814684e7ba1419cdaff2fb56b?pvs=74">[notion] cbow</a>

      - layout: left
        title: Elasticsearch 기능 확장
        caption: Elasticsearch-Plugin
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          Java, Elasticsearch, Maven

          **주요 기능 :**
          색인 대상에 대한 텍스트 필터링 및 토큰화, REST API

          **상세 설명 :**
          Elasticsearch의 기능을 확장하기 위해 커스텀 플러그인 개발. 
          이 플러그인은 특정 요구 사항에 맞춘 검색 기능을 추가하거나, 데이터를 
          효율적으로 인덱싱하고 검색할 수 있는 새로운 방법을 제공함.

          **Link :**
          <a href="https://canyon-nickel-820.notion.site/Elasticsearch-plugin-86de562db42d4468b8cadfb8ac37dc44?pvs=74">[notion] elasticsearch plugin</a>

      - layout: left
        title: 파일 관리 프로그램
        caption: KEY-HOOK, GUI
        description: | # this will include new lines to allow paragraphs
          **사용 기술 :**
          JAVA ( thread, jna, swing,google drive api )

          **주요 기능 :**
          google drive api 를 사용하여 저장소에 최신버전이 있을경우 자동 다운로드 가능하고
          파일이나 폴더에 빠르게 접근할수있는 다양한 기능 제공

          **상세 설명 :**
          프로젝트마다 복잡한 디렉터리 구조를 파악하기 곤란한 상황에 태그, 날짜, 체크리스트 
          검색으로 파일이나 폴더에 보다 빨리 접근 하기위해 만들어진 프로젝트로 개인 업무향상
          을 위해 만든 프로그램이다. 
          파일및 폴더를 lnk 복사 하여 원본파일의 위치, 파일명, 내용 변경에 영향을 받지 않는다.

          **Link :**
          <a href="https://www.notion.so/8788e6ad16ce4a6c88971c906840c254?showMoveTo=true&saveParent=true">[notion] file manager</a>

      - layout: left
        title: 알고리즘 학습
        caption: 온라인 코딩테스트 문제풀이
        description: | # this will include new lines to allow paragraphs
          **상세 설명 :**
          온라인에서 제공하는 코딩테스트 1일 1문제 풀이를 목적으로 개설된 프로젝트이다.
          주로 해시, 스택, 큐, 힙, 그리디, 정렬, DP, DFS/BFS, 이분탐색에 대한 이해와 학습의 
          목적으로 매일 업데이트 된다. 업데이트된 내용은 풀이코드와 베스트 코드가 있으며 
          fail 된 사유가 적혀있다.

          **Link :**
          <a href="https://github.com/sihyeonleee/AlgorithmPractice">[github] algorithm practicer</a>

  - title: Background
    layout: list
    content:
      - layout: left
        title: 최종학력
        sub_title: 학점평균 3.79
        caption: 2016. 03 ~ 2019. 02
        description: | # this will include new lines to allow paragraphs
          **영진전문대학교 - 컴퓨터 정보계열**
          ---
          <table>
            <tr>
              <th>년도</th> <th>학년</th> <th>학기</th> <th>신청학점</th> <th>취득학점</th> <th>교필</th> <th>교선</th> 
              <th>전필</th> <th>전선</th>	<th>교직</th> <th>인접</th> <th>평점계</th> <th>평균평점</th> <th>점수계</th> <th>점수평균</th> 
            </tr>
            <tr>
              <td>2016</td> <td>1</td> <td>1</td> <td>20</td> <td>20</td> <td>0</td> <td>3</td> <td>0</td> <td>17</td> <td>0</td> <td>0</td> <td>76.00</td> <td>4.00</td> <td>1,762</td> <td>92.74</td>
            </tr>
            <tr>
              <td>2016</td> <td>1</td> <td>2</td> <td>23</td> <td>23</td> <td>0</td> <td>3</td> <td>0</td> <td>20</td> <td>0</td> <td>0</td> <td>96.00</td> <td>4.36</td> <td>2,111</td> <td>95.95</td>
            </tr>
            <tr>
              <td>2017</td> <td>2</td> <td>1</td> <td>24</td> <td>24</td> <td>1</td> <td>2</td> <td>0</td> <td>21</td> <td>0</td> <td>0</td> <td>91.50</td> <td>3.98</td> <td>2,096</td> <td>91.13</td>
            </tr>
            <tr>
              <td>2017</td> <td>2</td> <td>2</td> <td>24</td> <td>24</td> <td>0</td> <td>2</td> <td>0</td> <td>22</td> <td>0</td> <td>0</td> <td>84.00</td> <td>3.50</td> <td>2,065</td> <td>86.04</td>
            </tr>
            <tr>
              <td>2018</td> <td>3</td> <td>1</td> <td>20</td> <td>20</td> <td>0</td> <td>2</td> <td>3</td> <td>15</td> <td>0</td> <td>0</td> <td>55.50</td> <td>2.92</td> <td>1,524</td> <td>80.21</td>
            </tr>
            <tr>
              <td>2018</td> <td>3</td> <td>2</td> <td>9 </td> <td>9	</td> <td>0</td> <td>0</td> <td>3</td> <td>6 </td> <td>0</td> <td>0</td> <td>33.00</td> <td>4.13</td> <td>739	 </td> <td>92.38</td>
            </tr>
            <tr>
              <td>2018</td> <td>3</td> <td>3</td> <td>3 </td> <td>3	</td> <td>0</td> <td>0</td> <td>3</td> <td>0 </td> <td>0</td> <td>0</td> <td>0.00 </td> <td>0.00</td> <td>0	   </td> <td>0.00 </td>
            </tr>
            <tr>
              <td>계</td> <td></td> <td></td> <td>123</td> <td>123</td> <td>1</td>	<td>12</td> <td>9</td> <td>101</td> <td>0</td> <td>0</td> <td>436</td> <td>3.79</td> <td>10,297</td> <td>89.54</td>
            </tr>
          </table>

      - layout: left
        title: 동아리
        sub_title: 교내활동
        description: | # this will include new lines to allow paragraphs
          **해커스랩**
          ---
          - 동아리 목적 : 프로그래밍 역량강화 및 취업활동에 이점을 가지기 위함.
          - 활동 내역 : 
            1. "스마트팜" 아두이노 스마트 식물 발아기 개발
            2. 전국 대학생 대상 it 컨퍼런스 참가 및 수상
            3. 교내에서 진행하는 창업 지원 프로그램 참가
            4. 프로그래밍 강화 목적을 위한 멘토 멘티 결성

      - layout: left
        title: 블로그
        sub_title: 교과목
        description: | # this will include new lines to allow paragraphs
          **NAVER BLOG**
          ---
          - NAVER 블로그 : <a href="https://blog.naver.com/dltlgus313">Blog URL</a>
          - 블로그 운영 목적 : 교과목에 대한 이해와 개인 역량 강화를 위함이며 정리의 목적.
          - 운영 과목 : C 언어, Java 언어, RDBMS, 리눅스, CS, CCNA 등

      - layout: left
        title: 프로젝트
        sub_title: 과제
        description: | # this will include new lines to allow paragraphs
          - `Line Tracer` 개발 
            1. 제공되는 자원 한정 및 C++ 언어 사용
            2. 배터리 및 기타 모듈등 최적의 성능을 발휘하도록 배치
            3. 가장 짧은 시간안에 도착한 팀이 우승하며 약 20개팀 중 1등.
          - Starcraft, Maple story 등 유명 게임 벤치마킹한 온라인 2d 횡스크롤 게임 `StarWar2d` 개발
            1. TCP, UDP 를 적절히 활용하여 오픈 월드 구축
            2. PvP 시스템을 구축하여 사용자간의 결투 가능
            3. 미니맵 구축 우상단에 몬스터외 사용자 위치 파악 가능
            4. 상점및 아이템 구성, 단축키, 몬스터 처치시 확률성 아이템드롭률 구축
          - 프로젝트 진행시 방법론을 접목하여 전체 프로젝트를 관리 가능한 `TaskDoc` 개발 
            1. 앱, 웹간의 연동 및 실시간 통신을 위해 STOMP를 이용하여 구독 메시징 프로토콜 적용
            2. 프로젝트 관리에 적합한 간트차트 Component 안드로이드 직접 개발하여 배포 완료 <a href="https://github.com/dltlgus312/Ganttchart-Android">[Android] Ganttchart</a>
            3. 웹 & 앱에 모두 대응되는 REST API 형태의 서버 코드 개발
            4. Link: <a href="https://github.com/dltlgus312/TaskDoc-WEB-SERVER">[Web] TaskDoc</a>, <a href="https://github.com/dltlgus312/TaskDoc-ANDROID">[Android] TaskDoc</a>

  - title: Certificate
    layout: list
    content:
      - layout: center
        title: 정보처리기사
        sub_title: 한국산업인력공단
        caption: 2021. 08
        description: | # this will include new lines to allow paragraphs
          <h1>정보처리기사</h1>
          ---
          <img width="150px" height="220px" src="images/cert_infomation_engineer.png">
      - layout: center
        title: 리눅스
        sub_title: 한국정보통신인력개발센터
        caption: 2017. 04
        description: | # this will include new lines to allow paragraphs
          <h1>리눅스마스터 2급</h1>
          ---
          <img width="150px" height="220px" src="images/cert_linux_master.png">
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      저의 IT 커리어는 많은 고민 끝에 시작되었습니다. 처음에는 독학으로 프로그래밍을 배우기 시작했지만, 
      생각처럼 결과물을 만들기 어려워 대학에 진학하게 되었습니다. 대학에서 첫 홈페이지를 만들면서, 
      시간가는 줄 모르고 작업에 몰두하는 저 자신을 보며 이 길이 제 길이라는 확신을 가지게 되었습니다. 
      그 이후로, **"개발은 0에서 시작하여 무엇이든 창조할 수 있다"**는 신념 아래 게임, 홈페이지, IoT 
      등 다양한 프로젝트를 진행하며 개발자의 길을 걸어왔습니다.

      첫 회사에서는 COVID-19에 대응하여 초중고 교육을 위한 "온라인 클래스" 프로젝트에 참여했습니다. 
      이 프로젝트는 일 접속량이 100만이 넘는 대규모 프로젝트였고 이를 통해 설계, 구성, 트래픽관리, 
      쿼리 최적화 등 다양한 각도에서 개발을 경험했습니다. 이 경험을 바탕으로 **MSA, Multitenant,
      master-slave** 구조 등을 공부하고, 이를 새로운 프로젝트에 적용해보는 기회를 얻었습니다.

      개발 과정에서 더 나은 방법을 찾고자 항상 노력하고 코드 리팩토링에 대해 자주 고민합니다. 
      모르는 용어나 신기술에 민감하고 기존 프로젝트와 비교하는 습관이 있습니다. 시스템 구성도와 
      프로젝트 설계에도 관심이 있으며 단축키, 유틸리티, 플러그인 등 주변 도구를 활용하여 업무의 
      능률을 높이는 것을 좋아합니다. 필요에 따라 직접 애플리케이션을 개발하여 업무 처리속도를 
      향상시키고, 이러한 마인드 덕분에 손이 빠르다는 평가를 자주 받습니다.

      업무상 긍정적인 성격과 웃는 얼굴로 동료간 의견 수립에 거부감이 없고 가능/불가능에 연연하지 
      않아 능력 범위 내에서 최선을 다합니다. 또한 책임감을 가지고 프로젝트에 대해 자주 고민하며
      이를 통해 인정받는 것을 좋아합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
